export default {
  "login": "AbHaY108BiShT",
  "id": 75539409,
  "node_id": "MDQ6VXNlcjc1NTM5NDA5",
  "avatar_url": "https://avatars.githubusercontent.com/u/75539409?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AbHaY108BiShT",
  "html_url": "https://github.com/AbHaY108BiShT",
  "followers_url": "https://api.github.com/users/AbHaY108BiShT/followers",
  "following_url": "https://api.github.com/users/AbHaY108BiShT/following{/other_user}",
  "gists_url": "https://api.github.com/users/AbHaY108BiShT/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AbHaY108BiShT/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AbHaY108BiShT/subscriptions",
  "organizations_url": "https://api.github.com/users/AbHaY108BiShT/orgs",
  "repos_url": "https://api.github.com/users/AbHaY108BiShT/repos",
  "events_url": "https://api.github.com/users/AbHaY108BiShT/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AbHaY108BiShT/received_events",
  "type": "User",
  "site_admin": false,
  "name": "aBhAy_BiShT",
  "company": null,
  "blog": "",
  "location": "In Your Imagination",
  "email": null,
  "hireable": null,
  "bio": "✔Python \r\n✔JavaScript\r\n✔HTML\r\n✔CSS\r\n✔Django\r\n✔Data-science\r\n✔noob game dev.😃\r\n💚currently working on Node-Js  and React\r\n👩‍💻\r\n=>Esports player🎮\r\n\r\n",
  "twitter_username": null,
  "public_repos": 55,
  "public_gists": 0,
  "followers": 2,
  "following": 15,
  "created_at": "2020-12-05T17:13:48Z",
  "updated_at": "2021-05-29T07:33:01Z"
}